### ISSUE TITLE
Don't use ReplaySubject

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/rx#1]
<img width="662" alt="screen shot 2016-07-29 at 4 10 34 pm" src="https://cloud.githubusercontent.com/assets/2053478/17263509/1cf947ea-55a7-11e6-8356-ef308ce708df.png">

**Comment by mkoczorowski** [comment]
Has this been fixed? I'm not sure to use this plugin. Last thing I need is a me more leak :)

**Comment by christopherthielen** [comment]
Whoops... yes, this is fixed.

https://github.com/ui-router/rx/blob/f8c011dbefb35164350e1ce95fab20c7497d8cba/src/ui-router-rx.ts#L34
