### ISSUE TITLE
Rollup as runtime dependency?

### ISSUE THREAD

**Issue by DaSchTour** [ui-router/rx#5]
Is rollup a runtime dependency? If not I guess it should be moved to devDependencies because the current definition forces JSPM to install all this packages and serve them to ui-router/rx

Instead rxjs and ui-router/core should be dependencies because they are needed at runtime.

**Comment by christopherthielen** [comment]
8bfa2a4d1aeb7780b80e1145ded8ce7e989a1e5c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
